[package]
name = "async_ucx_glommio_rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
async-ucx = "0.1.1"
futures = "0.3.31"
glommio = "0.9.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
